#include "E_STAT.h"


struct IStatInfo
{
	E_STAT Id;
	const char *Title;
};

const IStatInfo STAT_INFOS[] =
{
	{DST_NONE, ""},
	{DST_STR, "DST_STR"},
	{DST_DEX, "DST_STA"},
	{DST_INT, "DST_INT"},
	{DST_STA, "DST_STA"},
	{DST_YOY_DMG, "DST_YOY_DMG"},
	{DST_BOW_DMG, "DST_BOW_DMG"},
	{DST_CHR_RANGE, "DST_CHR_RANGE"},
	{DST_BLOCK_RANGE, "DST_BLOCK_RANGE"},
	{DST_CHR_CHANCECRITICAL, "DST_CHR_CHANCECRITICAL"},
	{DST_CHR_BLEEDING, "DST_CHR_BLEEDING"},
	{DST_SPEED, "DST_SPEED"},
	{DST_ABILITY_MIN, "DST_ABILITY_MIN"},
	{DST_ABILITY_MAX, "DST_ABILITY_MAX"},
	{DST_BLOCK_MELEE, "DST_BLOCK_MELEE"},
	{DST_MASTRY_EARTH, "DST_MASTRY_EARTH"},
	{DST_STOP_MOVEMENT, "DST_STOP_MOVEMENT"},
	{DST_MASTRY_FIRE, "DST_MASTRY_FIRE"},
	{DST_MASTRY_WATER, "DST_MASTRY_WATER"},
	{DST_MASTRY_ELECTRICITY, "DST_MASTRY_ELECTRICITY"},
	{DST_MASTRY_WIND, "DST_MASTRY_WIND"},
	{DST_KNUCKLE_DMG, "DST_KNUCKLE_DMG"},
	{DST_PVP_DMG_RATE, "DST_PVP_DMG_RATE"},
	{DST_NONE, ""},
	{DST_ATTACKSPEED, "DST_ATTACKSPEED"},
	{DST_SWD_DMG, "DST_SWD_DMG"},
	{DST_ADJDEF, "DST_ADJDEF"},
	{DST_RESIST_MAGIC, "DST_RESIST_MAGIC"},
	{DST_RESIST_ELECTRICITY, "DST_RESIST_ELECTRICITY"},
	{DST_REFLECT_DAMAGE, "DST_REFLECT_DAMAGE"},
	{DST_RESIST_FIRE, "DST_RESIST_FIRE"},
	{DST_RESIST_WIND, "DST_RESIST_WIND"},
	{DST_RESIST_WATER, "DST_RESIST_WATER"},
	{DST_RESIST_EARTH, "DST_RESIST_EARTH"},
	{DST_AXE_DMG, "DST_AXE_DMG"},
	{DST_HP_MAX, "DST_HP_MAX"},
	{DST_MP_MAX, "DST_MP_MAX"},
	{DST_FP_MAX, "DST_FP_MAX"},
	{DST_HP, "DST_HP"},
	{DST_MP, "DST_MP"},
	{DST_FP, "DST_FP"},
	{DST_HP_RECOVERY, "DST_HP_RECOVERY"},
	{DST_MP_RECOVERY, "DST_MP_RECOVERY"},
	{DST_FP_RECOVERY, "DST_FP_RECOVERY"},
	{DST_KILL_HP, "DST_KILL_HP"},
	{DST_KILL_MP, "DST_KILL_MP"},
	{DST_KILL_FP, "DST_KILL_FP"},
	{DST_ADJ_HITRATE, "DST_ADJ_HITRATE"},
	{DST_NONE, ""},
	{DST_CLEARBUFF, "DST_CLEARBUFF"},
	{DST_CHR_STEALHP_IMM, "DST_CHR_STEALHP_IMM"},
	{DST_ATTACKSPEED_RATE, "DST_ATTACKSPEED_RATE"},
	{DST_HP_MAX_RATE, "DST_HP_MAX_RATE"},
	{DST_MP_MAX_RATE, "DST_MP_MAX_RATE"},
	{DST_FP_MAX_RATE, "DST_FP_MAX_RATE"},
	{DST_CHR_WEAEATKCHANGE, "DST_CHR_WEAEATKCHANGE"},
	{DST_CHR_STEALHP, "DST_CHR_STEALHP"},
	{DST_CHR_CHANCESTUN, "DST_CHR_CHANCESTUN"},
	{DST_AUTOHP, "DST_AUTOHP"},
	{DST_CHR_CHANCEDARK, "DST_CHR_CHANCEDARK"},
	{DST_CHR_CHANCEPOISON, "DST_CHR_CHANCEPOISON"},
	{DST_IMMUNITY, "DST_IMMUNITY"},
	{DST_ADDMAGIC, "DST_ADDMAGIC"},
	{DST_CHR_DMG, "DST_CHR_DMG"},
	{DST_CHRSTATE, "DST_CHRSTATE"},
	{DST_PARRY, "DST_PARRY"},
	{DST_ATKPOWER_RATE, "DST_ATKPOWER_RATE"},
	{DST_EXPERIENCE, "DST_EXPERIENCE"},
	{DST_JUMPING, "DST_JUMPING"},
	{DST_CHR_CHANCESTEALHP, "DST_CHR_CHANCESTEALHP"},
	{DST_CHR_CHANCEBLEEDING, "DST_CHR_CHANCEBLEEDING"},
	{DST_RECOVERY_EXP, "DST_RECOVERY_EXP"},
	{DST_ADJDEF_RATE, "DST_ADJDEF_RATE"},
	{DST_MP_DEC_RATE, "DST_MP_DEC_RATE"},
	{DST_FP_DEC_RATE, "DST_FP_DEC_RATE"},
	{DST_SPELL_RATE, "DST_SPELL_RATE"},
	{DST_CAST_CRITICAL_RATE, "DST_CAST_CRITICAL_RATE"},
	{DST_CRITICAL_BONUS, "DST_CRITICAL_BONUS"},
	{DST_SKILL_LEVEL, "DST_SKILL_LEVEL"},
	{DST_MONSTER_DMG, "DST_MONSTER_DMG"},
	{DST_PVP_DMG, "DST_PVP_DMG"},
	{DST_MELEE_STEALHP, "DST_MELEE_STEALHP"},
	{DST_HEAL, "DST_HEAL"},
	{DST_ATKPOWER, "DST_ATKPOWER"},
	{DST_NONE, ""},
	{DST_ONEHANDMASTER_DMG, "DST_ONEHANDMASTER_DMG"},
	{DST_TWOHANDMASTER_DMG, "DST_TWOHANDMASTER_DMG"},
	{DST_YOYOMASTER_DMG, "DST_YOYOMASTER_DMG"},
	{DST_BOWMASTER_DMG, "DST_BOWMASTER_DMG"},
	{DST_KNUCKLEMASTER_DMG, "DST_KNUCKLEMASTER_DMG"},
	{DST_HAWKEYE_RATE, "DST_HAWKEYE_RATE"},
	{DST_RESIST_MAGIC_RATE, "DST_RESIST_MAGIC_RATE"},
	{DST_GIFTBOX, "DST_GIFTBOX"},
	{MAX_ADJPARAMARY, "MAX_ADJPARAMARY"},
	{DST_GOLD, "DST_GOLD"},
	{DST_PXP, "DST_PXP"},
	{DST_RESIST_ALL, "DST_RESIST_ALL"},
	{DST_STAT_ALLUP, "DST_STAT_ALLUP"},
	{DST_HPDMG_UP, "DST_HPDMG_UP"},
	{DST_DEFHITRATE_DOWN, "DST_DEFHITRATE_DOWN"},
	{DST_CURECHR, "DST_CURECHR"},
	{DST_HP_RECOVERY_RATE, "DST_HP_RECOVERY_RATE"},
	{DST_MP_RECOVERY_RATE, "DST_MP_RECOVERY_RATE"},
	{DST_FP_RECOVERY_RATE, "DST_FP_RECOVERY_RATE"},
	{DST_LOCOMOTION, "DST_LOCOMOTION"},
	{DST_MASTRY_ALL, "DST_MASTRY_ALL"},
	{DST_ALL_RECOVERY, "DST_ALL_RECOVERY"},
	{DST_ALL_RECOVERY_RATE, "DST_ALL_RECOVERY_RATE"},
	{DST_KILL_ALL, "DST_KILL_ALL"},
	{DST_KILL_HP_RATE, "DST_KILL_HP_RATE"},
	{DST_KILL_MP_RATE, "DST_KILL_MP_RATE"},
	{DST_KILL_FP_RATE, "DST_KILL_FP_RATE"},
	{DST_KILL_ALL_RATE, "DST_KILL_ALL_RATE"},
	{DST_ALL_DEC_RATE, "DST_ALL_DEC_RATE"}
};


E_STAT stat(const char *_title)
{
	for (u32 i = 0; i < ARRAY_SIZE(STAT_INFOS); ++i)
	{
		if (strcmp(STAT_INFOS[i].Title, _title) == 0)
		{
			return STAT_INFOS[i].Id;
		}
	}

	return DST_STR;
}

E_STAT stat(s32 _id)
{
	return E_STAT(Limit<s32>(_id, 0, DST_GIFTBOX));
}

const char *statTitle(E_STAT _stat)
{
	if (_stat >= 0 &&
		_stat < COUNT_OF_STATS)
	{
		return STAT_INFOS[_stat].Title;
	}

	return "";
}
